### ISSUE TITLE
Do you want tests to run in pull requests

### ISSUE THREAD

**Issue by martypowell** [aaaantoine/diceroll#31]
~~We can~~ You could use github actions to run these tests on prs. If the test fails the pr will be blocked as long as that check is setup in the settings of this repo. Let me know if you want this, we have a [template](https://github.com/baltimorecounty/react-transient-tax/blob/integration/.github/workflows/nodejs.yml) for this already.

**Comment by aaaantoine** [comment]
The repo is already supposed to be running checks on pull requests (see previous pull requests).  Not sure why it didn't run for #30...

**Comment by aaaantoine** [comment]
I think I see what's going on. [Line 3 here](https://github.com/aaaantoine/diceroll/blob/master/.github/workflows/nodejs.yml) only specifies `on: [push]` and doesn't include `pull-request`.
